dist: trusty
sudo: required
language: node_js
node_js:
  - 8
before_script:
  - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
  - npm install -g @angular/cli@6.0.8
script:
  - ./build.sh
addons:
  chrome: stable
